### PR TITLE
Tutorial 12 - Render Target

### PR DESCRIPTION
**Pull request by dolphineye**
# Motivations
In this pull request, I propose to add a new tutorial to show a how use a render target to achieve some post-processing effect with the Diligent Engine.

# Proposed solution
I wanted to focus on the render target related code, so I stripped all the vertex buffer, index buffer and texturing part from the code.

I also provide a simple `readme.md` file that gives some indication of the different steps involves in creating and using a render target. Once again, I stripped all the documentation covered by previous tutorials.

Let me know if you feel that I should change a few things ;)

# Testing done
Windows 64 bits with OpenGL 4.4.X and Vulkan 1.X.

### CODE REVIEW

**Comment by DiligentGraphics** [comment]
Hi, thanks for contributing this tutorial!
I made few changes and pushed them to your PR
1. Constructs like this
```HLSL
float3 Pos[] =
{
    float3(-1, -1, -1),
    ....
 };
```
do not properly map to GLSL syntax. Some GLSL compilers handle them properly, but some GLES compilers fail.

2. This may also fail on GLES because `2` is the constant of type `int` which GLES compilers do not want to implicitly convert to `uint`:
```HLSL
uint Indices[] =
{
    2,0,1, 2,3,0,
    ...
};
```
3. Again, ES3.0 compiler may not like f suffix in `1.0f`
4. HLSL compiler does not like `float2(0.5)`,  should be `float2(0.5, 0.5)`
5. I also made few minor changes in to the source files:
  - Added clear value that D3D12 backend wants
  - Renamed some variables to use D3D-style (attachment -> render target)

I have one general suggestion: can you add some kind of animation to the post-processing effect, because it is little unclear where the render target is in this example. Maybe something like this:
wave spectrum10


Also, the render targets should likely be re-created when the window resizes.

**Comment by DiligentGraphics** [comment]
https://github.com/DiligentGraphics/DiligentSamples/commits/dolphineye-dolphineye/tutorial_012_rt

**Comment by DiligentGraphics** [comment]
I guess it is probably better to render textured cube here because it will better show what's going on with the distortion

**Comment by dolphineye** [comment]
As you wish. it shouldn't take long to add some texturing anyway :)

**Comment by DiligentGraphics** [comment]
Yeah, texturing would help since right now it is hard to tell that the thing is actually a cube

**Comment by dolphineye** [comment]
By the way, for the effect, I'd rather have this:

```diff
- float2 DistortedUV = UV + float2(sin(UV.y*30.0)*0.1 * sin(g_Time.x*3.0), sin(UV.x*20.0)*0.02 * sin(g_Time.x*2.0));
+ float2 DistortedUV = UV + float2(sin(UV.y*300.0)*0.1 * sin(g_Time.x*3.0), sin(UV.x*200.0)*0.02 * sin(g_Time.x*2.0));
```

Here's the resulting visuals:

tutorial12

I find it more cool that way :)

**Comment by DiligentGraphics** [comment]
Yeah, that certainly looks more interesting!

**Pull request merged**
